// Gegevens van eenheden, gebouwen en levels. Overgenomen uit de 2D-versie (orkenstorm.html).
// Afstanden en snelheden zijn in "pixels" van 32 per tegel, net als in 2D; tijden in beeldjes (60 per seconde).

export const UNIT = {
  werker: { n: 'Werker', hp: 30, dmg: 3, rng: 22, cd: 60, spd: 1.1, sight: 4, side: 'h', cost: [50, 0], time: 300, from: ['kasteel'] },
  soldaat: { n: 'Soldaat', hp: 60, dmg: 8, rng: 22, cd: 50, spd: 1, sight: 4, side: 'h', cost: [60, 10], time: 420, from: ['kazerne'] },
  boog: { n: 'Boogschutter', hp: 40, dmg: 6, rng: 130, cd: 70, spd: 1, sight: 5, side: 'h', cost: [50, 25], time: 420, from: ['kazerne'] },
  ork: { n: 'Ork', hp: 55, dmg: 8, rng: 22, cd: 55, spd: 0.9, sight: 4, side: 'o' },
  genezer: { n: 'Genezer', hp: 30, dmg: 2, rng: 22, cd: 60, spd: 1, sight: 4, side: 'h' },
  held: { n: 'Sir Lodewijk', hp: 140, dmg: 12, rng: 22, cd: 45, spd: 1.05, sight: 5, side: 'h' },
  skelet: { n: 'Skelet', hp: 45, dmg: 7, rng: 22, cd: 55, spd: 0.85, sight: 4, side: 'o' },
  speerork: { n: 'Speerwerper', hp: 35, dmg: 6, rng: 110, cd: 75, spd: 0.9, sight: 5, side: 'o' },
};

export const BLD = {
  kasteel: { n: 'Kasteel', w: 3, h: 3, hp: 400, food: 4, side: 'h' },
  boerderij: { n: 'Boerderij', w: 2, h: 2, hp: 120, food: 4, cost: [50, 30], time: 600, side: 'h' },
  kazerne: { n: 'Kazerne', w: 3, h: 3, hp: 250, cost: [100, 60], time: 900, side: 'h' },
  toren: { n: 'Toren', w: 2, h: 2, hp: 150, cost: [80, 50], time: 700, side: 'h', dmg: 7, rng: 160, cd: 70 },
  orkhut: { n: 'Orkenhut', w: 2, h: 2, hp: 250, side: 'o' },
  kooi: { n: 'Gevangenis', w: 2, h: 2, hp: 200, side: 'o' },
};

export const DIFF = [
  { n: 'Makkelijk', hp: 0.7, dmg: 0.7, wave: 1.35, extra: -1, res: 1.5 },
  { n: 'Normaal', hp: 1, dmg: 1, wave: 1, extra: 0, res: 1 },
  { n: 'Moeilijk', hp: 1.35, dmg: 1.3, wave: 0.8, extra: 1, res: 0.8 },
];

export const LEVELS = [
  {
    naam: 'Het nieuwe dorp',
    brief: [
      'De koning geeft je een stukje land aan de rand van het bos.',
      'Bouw er een dorp met 4 boerderijen en een kazerne.',
      'Klik op een werker en daarna op een boom om hout te hakken,',
      'of op de goudmijn om goud te halen.',
      'Er zwerven orks rond onder de wolken. Ze laten je met rust',
      'zolang je niet te dichtbij komt.',
    ],
    doel: 'Bouw 4 boerderijen en een kazerne',
    goud: 150, hout: 80, bouw: ['boerderij', 'kazerne'],
    map: [
      'TTTTTTTT......TTTTTTTTTT',
      'TTTTTT..........TTTTTTTT',
      'TTTT..............TTTTTT',
      'TT.......MM........TTTTT',
      'T........MM.........TTTT',
      'T....................TTT',
      'TT...................TTT',
      'TTT.....WWWW..........TT',
      'TTT....WWWWWW.........TT',
      'TT.....WWWWWW..........T',
      'T.......WWWW...........T',
      'T......................T',
      '......................TT',
      'TT....................TT',
      'TTT..................TTT',
      'TTTT...........TT....TTT',
      'TTT...........TTTT....TT',
      'TT............TTTT.....T',
      'T..............TT......T',
      'T......................T',
      'TT.....................T',
      'TTT.......MM...........T',
      'TTT.......MM..........TT',
      'TT...................TTT',
      'T...................TTTT',
      'T..................TTTTT',
      'T.................TTTTTT',
      'TT.......TTT.....TTTTTTT',
      'TTTT.....TTTT.TTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    b: [['kasteel', 3, 24]],
    u: [['werker', 7, 25], ['werker', 7, 26], ['soldaat', 6, 23]],
    o: [['ork', 11, 5], ['ork', 7, 5], ['ork', 19, 11], ['ork', 3, 12], ['ork', 14, 2]],
    huts: [],
    win: (s) => s.count('boerderij') >= 4 && s.count('kazerne') >= 1,
    voortgang: (s) => `boerderijen <b>${Math.min(4, s.count('boerderij'))}/4</b> · kazerne <b>${Math.min(1, s.count('kazerne'))}/1</b>`,
  },
  {
    naam: 'De orks komen eraan',
    brief: [
      'Achter de rivier hebben de orks een kamp gebouwd.',
      'Steeds vaker steken ze de bruggen over om je dorp aan te vallen.',
      'Verdedig je dorp met soldaten, boogschutters en torens.',
      'Trek dan over een brug, zoek hun kamp onder de wolken',
      'en vernietig de orkenhutten.',
    ],
    doel: 'Vernietig de orkenhutten en versla alle orks',
    goud: 200, hout: 150, bouw: ['boerderij', 'kazerne', 'toren'],
    map: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTT............TTTTTT',
      'TTTT.........MM.......TT',
      'TTT..........MM........T',
      'TT.....................T',
      'T......................T',
      'T......TTT.............T',
      'TT....TTTTT............T',
      'TTT....TTT............TT',
      'TT...................TTT',
      'T.....................TT',
      'T......................T',
      'TT....................TT',
      'WWWWW=WWWWWWWWWWWW=WWWWW',
      'WWWWW=WWWWWWWWWWWW=WWWWW',
      'WWWWW=WWWWWWWWWWWW=WWWWW',
      'T......................T',
      'TT.........TTT.........T',
      'TTT.......TTTTT.......TT',
      'TT.........TTT........TT',
      'T......................T',
      'T......................T',
      'T......................T',
      'T...........MM.......TTT',
      'T...........MM......TTTT',
      'T..................TTTTT',
      'T..................TTTTT',
      'TT.................TTTTT',
      'TTTT.....TTTT....TTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    b: [['kasteel', 2, 24], ['boerderij', 6, 26], ['boerderij', 9, 26], ['kazerne', 6, 21]],
    u: [['werker', 5, 23], ['werker', 4, 22], ['werker', 3, 22], ['soldaat', 10, 20], ['soldaat', 11, 20], ['boog', 10, 21]],
    o: [['ork', 5, 11], ['ork', 18, 11], ['speerork', 17, 10], ['ork', 18, 5], ['ork', 15, 8], ['speerork', 19, 8]],
    huts: [[18, 4], [13, 8]],
    waves: { first: 7200, every: 5400 },
    win: (s) => s.huts() == 0 && s.orcs() == 0,
    voortgang: (s) => `orkenhutten nog <b>${s.huts()}</b> · orks nog <b>${s.orcs()}</b>`,
  },
  {
    naam: 'De gevangen werkers',
    brief: [
      'De orks hebben het dorp Zonnedal overvallen.',
      'Alle werkers zijn meegenomen en zitten opgesloten in een houten',
      'gevangenis in het orkenkamp, ergens in het noorden onder de wolken.',
      'Trek op met je soldaten, sla de gevangenis kapot en bevrijd ze.',
      'Daarna kun je weer hout hakken en goud halen:',
      'bouw 2 boerderijen en vernietig de orkenhut.',
    ],
    doel: 'Bevrijd de werkers, bouw 2 boerderijen, sloop de orkenhut',
    goud: 250, hout: 200, bouw: ['boerderij', 'kazerne', 'toren'],
    map: [
      'TTTTTTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTT........TTTTTT',
      'TTTTTTT...............TT',
      'TTTTT..................T',
      'TTTT...................T',
      'TTT....................T',
      'TT.....................T',
      'TT...........TT........T',
      'T...........TTTT.......T',
      'T...WWW......TT........T',
      'T..WWWWW...............T',
      'T..WWWWW.........TTT...T',
      'T...WWW.........TTTTT..T',
      'TT..............TTTTT..T',
      'TTT..............TTT...T',
      'TTTT...................T',
      'TTT....TTTT............T',
      'TT....TTTTTT.........TTT',
      'T......TTTT..........TTT',
      'T....................TTT',
      'T........MM..........TTT',
      'T........MM...........TT',
      'T......................T',
      'T......................T',
      'T......................T',
      'T...................TTTT',
      'T..................TTTTT',
      'TT.........TTT....TTTTTT',
      'TTTT.....TTTTTT.TTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    b: [['kasteel', 3, 23]],
    u: [['soldaat', 7, 22], ['soldaat', 8, 22], ['soldaat', 7, 23], ['soldaat', 8, 23], ['boog', 9, 22], ['boog', 9, 23]],
    o: [['ork', 14, 6], ['ork', 18, 6], ['ork', 13, 4], ['speerork', 16, 7], ['speerork', 12, 6], ['ork', 10, 13], ['ork', 19, 15]],
    huts: [[19, 2]],
    kooi: [[15, 4]],
    waves: { first: 10800, every: 7200 },
    win: (s) => s.vrij() && s.huts() == 0 && s.count('boerderij') >= 2,
    voortgang: (s) => `werkers <b>${s.vrij() ? 'bevrijd ✓' : 'gevangen'}</b> · boerderijen <b>${Math.min(2, s.count('boerderij'))}/2</b> · orkenhut nog <b>${s.huts()}</b>`,
  },
  {
    naam: 'De Donkere Mijnen', dungeon: 1,
    brief: [
      'De dappere ridder Sir Lodewijk is verdwenen in de Donkere Mijnen.',
      'Volgens de verhalen houden orks en skeletten hem daar gevangen.',
      'Daal af met je soldaten, je boogschutters en een genezer.',
      'De genezer maakt gewonde mannetjes vanzelf weer beter.',
      'Zoek Sir Lodewijk, bevrijd hem en breng hem levend',
      'terug naar de trap waar je naar binnen kwam.',
    ],
    doel: 'Vind Sir Lodewijk en breng hem naar de uitgang',
    goud: 0, hout: 0, bouw: [],
    held: [3, 2],
    map: [
      '########################',
      '#......####............#',
      '#......####............#',
      '#......####....###.....#',
      '#......####....###.....#',
      '###..######....#t#.....#',
      '###..#t####...........##',
      '###.........######..####',
      '######......####t#..####',
      '######..##..........####',
      '#.......##..........####',
      '#..###..########....####',
      '#..##t..########.......#',
      '#.......####...........#',
      '####....####...#####...#',
      '####..######...#t###...#',
      '####..######.........###',
      '#.........###........###',
      '#.........###..#########',
      '#...###...###..#########',
      '#...tt#..........#######',
      '#........###.....#######',
      '######...###.....#######',
      '######.......##..#######',
      '#######......##..#######',
      '#######...............##',
      '########.........#######',
      '#########.......########',
      '##########EEEE##########',
      '########################',
    ],
    b: [],
    u: [['soldaat', 10, 26], ['soldaat', 11, 26], ['soldaat', 12, 26], ['soldaat', 13, 26], ['boog', 11, 27], ['boog', 12, 27], ['genezer', 10, 27]],
    o: [['skelet', 8, 23], ['skelet', 14, 21], ['ork', 3, 18], ['speerork', 7, 17], ['skelet', 2, 12], ['ork', 6, 10], ['ork', 12, 9], ['skelet', 18, 10], ['speerork', 17, 13],
      ['ork', 8, 7], ['skelet', 10, 7], ['ork', 5, 3], ['speerork', 2, 4], ['ork', 5, 1], ['skelet', 19, 3], ['skelet', 14, 2], ['ork', 1, 10], ['skelet', 3, 13], ['skelet', 9, 18], ['ork', 16, 20], ['speerork', 15, 24]],
    huts: [],
    ambush: [[5, 12], [2, 17], [8, 21], [12, 24], [6, 9]],
    win: (s) => s.heldUit(),
    voortgang: (s) => (s.heldVrij() ? 'Sir Lodewijk <b>bevrijd ✓</b> · breng hem naar de <b>trap</b> (onderaan)' : 'zoek <b>Sir Lodewijk</b> in de mijnen'),
  },
];

// Waar de mannetjes vandaan komen: wat ze vasthouden en wat werkers extra kunnen
export const LAND = {
  nl: { n: 'Nederlander', ding: 'een kaasje', effect: 'Zuinig: brengt 2 goud extra mee uit de mijn' },
  en: { n: 'Engelsman', ding: 'een kopje thee', effect: 'Hakt sneller hout, maar houdt af en toe theepauze' },
  de: { n: 'Duitser', ding: 'een pul', effect: 'Grondig: bouwt sneller' },
  it: { n: 'Italiaan', ding: 'een pizza', effect: 'Deelt pizza uit: geneest gewonde mannetjes vlakbij' },
  fr: { n: 'Fransman', ding: 'een stokbrood', effect: 'Snel: is maar kort in de goudmijn' },
};

// Levels uit de 2D-versie die nog naar 3D moeten
export const BINNENKORT = ['Het Woud van Elwynn', 'De belegerde abdij'];
